env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
globals:
  URL: readonly
  console: readonly
  process: readonly
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
